#+TITLE: Spiritual Mapping Project, Language Proposal
#+AUTHOR: Matt Lin
#+OPTIONS: toc:nil
* Purpose
  I am making this proposal as a rough draft of an easy to follow language that
  can be used to make a powerpoint.
* Language options
** Structure
   The overall structure of the language is to have one easy to follow command
   on each line, with as much inference as possible -- as long as the general
   structure is correct and the data is in the right place, that's really all
   that we need.
** General example
   #+BEGIN_EXAMPLE
   #title Cornell Survey, 2016
   #author Matthew Lin
   #slide Prayer vs reading the bible
   #chart <make this stuff up later>
   #textarea
   #slide More information goes here
   #textarea Conclusions go here
   #+END_EXAMPLE
   This should give us three slides: a title slide, a slide with a chart on the
   left and a textbox on the right, and another slide, with a full sized text
   box.
* Commands
** #title
   This is used to initialize the title slide of the presentation. Usage
   anywhere else in the program will result in undefined behavior. Omission of
   this will result in undefined behavior.
** #author
   This is used to put your name in the subtitle of the presentation. Usage
   anywhere else in the program will result in undefined behavior.
** #slide
   This is used to generate a new slide, and what comes afterwards is the title
   of the slide, placed at the top of the screen. As of now, each slide can have
   one, two, four, or six elements on it. Any other number of elements on a
   slide will result in undefined behavior.
** #text
   Anything that comes after this command is put into a PPT textbox. If you wish
   to have two columns for your textbox, use two #text commands to put them side
   by side.
** #chart
   This is a command to use to generate a chart.
** #
   If you wish to split your text or chart command along two lines, you can
   start the next line with a '#' and a space, and then continue on with your
   command. This may come useful if you want to have a long chart.
** Comments
   Comments are started with an empty space.
* Chart commands
** Pie charts
   #+BEGIN_EXAMPLE
   #chart pieslice: majors;[all,fellowship,aaIV,everyWeeker]
   # Representation in majors
   #+END_EXAMPLE
   Pie charts should be used for proportion or representation, given that each
   item has the same weight. Additionally, there should be relatively few number
   of categories, unless if the pie chart is used to make a point of
   disproportionate representation

   Pie charts can come in several varieties. The types that are included are the
   slicing type, where the data set is progressively trimmed down, and the
   remnants are assembled into a pie chart, and the assembled pie chart, where
   the data is joined together
*** Sliced pie chart
    #+BEGIN_EXAMPLE
    #chart pieslice: data_set [categories,in,order,of,filtering] Name of chart
    #+END_EXAMPLE
*** TODO Joined pie chart
    #+BEGIN_EXAMPLE
    #chart piesimple: data_set [categories,go,here] Name of chart
    #+END_EXAMPLE
* Where to generate the charts?
  I am using a node.js library called officegen, and it contains a way of
  making charts natively in powerpoint. I will play around with it some more
  so that we don't necessarily have to have charts as images, which would save
  some work for us.
